#!/usr/bin/env bash
#
# Define standard files required by other scripts, create them if they don't exist
#
# USAGE:
#   source functions/define_files
#
# NOTES:
#   Should appear in the initial stanza of all non-trivial scripts, even if they are not yet used
#   Put the string "files" in the environment variable DEBUG_XREF to turn on debugging
#
# EXAMPLE:
#       # Make sure we are in the correct directory
#       DIRNAME=$(dirname "$0")
#       cd "$DIRNAME"
#       source functions/define_colors  # Only if you want colors to be used in output
#       source functions/define_files
#       source functions/load_functions

# Standard files
configFile=".xref_config"
[ ! -e "$configFile" ] && touch "$configFile"

durationFile=".xref_durations"
[ ! -e "$durationFile" ] && touch "$durationFile"

# Look for the string "files" in $DEBUG_XREF to enable debugging
if [[ $DEBUG_XREF == *"files"* ]]; then
    printf "[${YELLOW}Debug-files${NO_COLOR}] Running:              $PWD/$(basename $0)\n" >&2
    printf "[${YELLOW}Debug-files${NO_COLOR}] Using configFile:     $PWD/$configFile\n" >&2
    printf "[${YELLOW}Debug-files${NO_COLOR}] Using durationFile:   $PWD/$durationFile\n" >&2
fi
