#!/usr/bin/env bash
#
# Define escape sequences that produce terminal colors
#
# USAGE:
#   . define_colors
#
#   printf "Do you prefer ${RED}Red${NO_COLOR} or ${BLUE}Blue${NO_COLOR}?\n"
#
# NOTES:
#   End any color escapes with ${NO_COLOR} to return to normal text.
#
#   The above printf will print as normal text if this file has not been sourced
#   so you can switch your preference between plain and colors by sourcing this file.

# Standard colors
BLACK="\e[0;30m"
RED="\e[0;31m"
GREEN="\e[0;32m"
YELLOW="\e[0;33m"
BLUE="\e[0;34;1m"
MAGENTA="\e[0;35m"
CYAN="\e[0;36m"
GRAY="\e[0;37m"
NO_COLOR="\e[0m"
