#!/usr/bin/env bash
#
# Load any files in the function directory named *.function
#
# USAGE:
#   source functions/load_functions
#
# NOTES:
#   Should appear in the initial stanza of all non-trivial scripts, even if they are not
#   yet used Put the string "load" in the environment variable DEBUG_XREF to turn on
#   debugging
#
# EXAMPLE:
#       # Make sure we are in the correct directory
#       DIRNAME=$(dirname "$0")
#       cd "$DIRNAME" || exit
#
#       source functions/define_colors  # Only if you want colors to be used in output
#       source functions/define_files
#       source functions/load_functions

# Make sure we pick up any global environment variables.
source $configFile

for file in $(ls functions/*.function); do
    source $file
    [[ $DEBUG_XREF == *"load"* ]] &&
        printf "[${YELLOW}Debug-load${NO_COLOR}] Loading: $(basename $file)\n"
done
