#!/usr/bin/env bash
#
# Remove all files and directories created by running scripts

# Make sure we are in the correct directory
DIRNAME=$(dirname "$0")
cd "$DIRNAME" || exit

source functions/define_colors
source functions/define_files
source functions/load_functions

function help() {
    cat <<EOF
cleanupEverything.sh -- Developer script: Remove files generated by other scripts.

This script makes it easier for developers to get rid of files generated by
running other scripts.  It will first ask if you want to delete EVERYTHING,
which will reset this directory to the state a completely new user would
encounter. You can't undo this.

If you hit <cr> or answer "no". It will give you the choice of deleting various
types of files, asked in order of increasing consequence. It always defaults to
"No", so just hit <cr> to see what your choices would be. Or look at the source
code for this script.

Note that your preferences file (~/.config/IMDb_xref/config) is never deleted.
It is shared by every clone of this project, so removing it here would change
the behavior of the others.

USAGE:
    ./cleanupEverything.sh [OPTIONS]

OPTIONS:
    -h      Print this message.
    -i      Request confirmation before attempting to remove each file
    -v      Be verbose when deleting files, showing them as they are removed.
EOF
}

function deleteFiles() {
    printf "Deleting ...\n"
    # Globbing needs to take place here.
    # shellcheck disable=SC2068      # Don't quote $@
    rm -rf "$ASK" "$TELL" $@
    printf "\n"
}

# Allow switches -v or -i to be passed to the rm command
while getopts ":hiv" opt; do
    case $opt in
    h)
        help
        exit
        ;;
    i)
        ASK="-i"
        ;;
    v)
        TELL="-v"
        ;;
    \?)
        printf "==> Ignoring invalid option: -$OPTARG\n\n" >&2
        ;;
    esac
done
shift $((OPTIND - 1))

# Quote filenames so globbing takes place in the "deleteFiles" function,
# i.e. the function is passed the number of parameters seen below, not
# the expanded list which could be quite long.
#
# The questions below run in order of increasing consequence: working files
# that every run recreates, then research spreadsheets nothing reads, then the
# files the scripts actually search, then generated state, then the slow
# download, and last the things you can't get back by re-running anything.
if waitUntil "$YN_PREF" -N \
    "${RED}Delete EVERYTHING created by scripts and users?${NO_COLOR}"; then
    deleteFiles "secondary" "diffs*.txt" "test_results" "Demo" \
        "AssociatedTitles*.csv" "Credits-Show*.csv" "Episode-Count*.csv" \
        "LinksToPersons*.csv" "LinksToTitles*.csv" "Persons-KnownFor*.csv" \
        "Shows-*.csv" "Credits-Person*.csv" "uniq*.txt" ".xref_bulk_*" \
        "*.tsv.gz" "*-Filmography" "*.tconst" "*.xlate"
    exit
else
    printf "Skipping...\n"
fi

# "secondary" is not a debugging artifact -- generateXrefData.sh creates it on
# every run to hold ~30 intermediate files, and empties it on exit unless DEBUG
# is set. "diffs*.txt" and "test_results" come only from -t. "Demo" is the
# self-contained corpus demo.command builds so its questions are answerable
# regardless of which shows the user has curated. The "baseline" directory this
# used to delete is a WhatsStreamingToday artifact that came across with the
# script; nothing here has ever created or read it.
if waitUntil "$YN_PREF" -N \
    "Delete working files, test baselines, and the demo corpus?"; then
    deleteFiles "secondary" "diffs*.txt" "test_results" "Demo"
else
    printf "Skipping...\n"
fi

# No script reads any of these -- generateXrefData.sh writes them and nothing
# else touches them. They exist so you can explore the data in a spreadsheet
# without learning any query syntax, which makes them the safest thing here to
# delete for space and the most annoying to have lost if you wanted them.
if waitUntil "$YN_PREF" -N \
    "Delete research spreadsheets of shows, episodes, links, and known-for titles?"; then
    deleteFiles "AssociatedTitles*.csv" "Credits-Show*.csv" "Episode-Count*.csv" \
        "LinksToPersons*.csv" "LinksToTitles*.csv" "Persons-KnownFor*.csv" \
        "Shows-*.csv"
else
    printf "Skipping...\n"
fi

# These two are the ones the tools query: xrefCast.sh and iQuery.sh search
# Credits-Person.csv, and iQuery.sh's category search plus start.command's
# "saved shows" listing read the uniq* lists. Deleting them stops those scripts
# working until generateXrefData.sh runs again -- which xrefCast.sh and
# iQuery.sh will offer to do for you.
if waitUntil "$YN_PREF" -N \
    "Delete the credits and list files that the scripts search?"; then
    deleteFiles "Credits-Person*.csv" "uniq*.txt"
else
    printf "Skipping...\n"
fi

# Only .xref_bulk_* -- a bare .xref_* glob would also delete the live-fetch
# branch's .xref_live_* state if someone has switched branches in this working
# directory, including a scraped cache that is slow and WAF-limited to rebuild.
#
# These are generated by scripts, not by the user, so this question belongs
# above the manually-created warning below. Note that actual user configuration
# lives in $configFile (~/.config/IMDb_xref/config), which is shared by every
# clone and is deliberately never deleted here.
if waitUntil "$YN_PREF" -N \
    "Delete the cross-reference cache and run history (.xref_bulk_*) files?"; then
    deleteFiles ".xref_bulk_*"
else
    printf "Skipping...\n"
fi

if waitUntil "$YN_PREF" -N "Delete all the .gz files downloaded from IMDb?"; then
    deleteFiles "*.tsv.gz"
else
    printf "Skipping...\n"
fi

printf "\n[${RED}Warning${NO_COLOR}] The following are created from your own input. "
printf "They are ignored by git.\n"

# Filmographies get their own question because each one exists only because you
# asked for that person. The data is local, so any single one can be rebuilt --
# but nothing records which people you chose, so with dozens saved you'd have to
# remember the list yourself.
if waitUntil "$YN_PREF" -N \
    "Delete all saved filmographies (*-Filmography)?"; then
    deleteFiles "*-Filmography"
else
    printf "Skipping...\n"
fi

if waitUntil "$YN_PREF" -N \
    "Delete all manually maintained .tconst and .xlate files?"; then
    deleteFiles "*.tconst" "*.xlate"
else
    printf "Skipping...\n"
fi
